WebApplication1/WebApplication1/Controllers/EMPRESA/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CapaEntidades;
using CapaDatos;
using System.Configuration;
using System.Data.SqlClient;


namespace WebApplication1.Controllers
{
    public class EmpresaController : Controller
    {
        private ProyectoPatronusWebEntities db = new ProyectoPatronusWebEntities();

        public ActionResult Free()
        {
            return View();
        }

        // GET: Empresa
        public ActionResult Index()
        {
            var Trabajo = db.Trabajoes.Include(t => t.Categoria).Include(t => t.EstadoTrabajo).Include(t => t.RegistroUsuario);
            return View(Trabajo.ToList());
        }

        // GET: Empresa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trabajo trabajo = db.Trabajoes.Find(id);
            if (trabajo == null)
            {
                return HttpNotFound();
            }
            return View(trabajo);
        }

        // GET: Empresa/Create
        public ActionResult Create()
        {
            ViewBag.idCategoria = new SelectList(db.Categorias, "idCategoria", "categoria1");                   //
            ViewBag.idEstado = new SelectList(db.EstadoTrabajoes, "idEstado", "estadoTrabajo1");         // Mostrara una lista con los datos de la base de datos
            ViewBag.idUsuario = new SelectList(db.RegistroUsuarios.Include(r => r.TipoUsuario).             //  
                Where(p => p.idTipoUsuario == 2 || p.idTipoUsuario == 4), "idUsuario", "nombreUsuario");  // Condiciona el llistado, solo mostrara los datos que sea de tipo Freelancer y no asignado.
            return View();
        }

        // POST: Empresa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
     

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idTrabajo,titulo,descripcion,idCategoria,fechaInicial,fechaAsignada,fechaFinal,idEstado,idUsuario,costoTrabajo")] Trabajo trabajo)
        {
            if (ModelState.IsValid)
            {
                db.Trabajoes.Add(trabajo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idCategoria = new SelectList(db.Categorias, "idCategoria", "categoria1", trabajo.idCategoria);
            ViewBag.idEstado = new SelectList(db.EstadoTrabajoes, "idEstado", "estadoTrabajo1", trabajo.idEstado);
            ViewBag.idUsuario = new SelectList(db.RegistroUsuarios, "idUsuario", "correo", trabajo.idUsuario);
            return View(trabajo);
        }

        // GET: Empresa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trabajo trabajo = db.Trabajoes.Find(id);
            if (trabajo == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCategoria = new SelectList(db.Categorias, "idCategoria", "categoria1", trabajo.idCategoria);
            ViewBag.idEstado = new SelectList(db.EstadoTrabajoes, "idEstado", "estadoTrabajo1", trabajo.idEstado);
            ViewBag.idUsuario = new SelectList(db.RegistroUsuarios, "idUsuario", "correo", trabajo.idUsuario);
            return View(trabajo);
        }

        // POST: Empresa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idTrabajo,titulo,descripcion,idCategoria,fechaInicial,fechaAsignada,fechaFinal,idEstado,idUsuario,costoTrabajo")] Trabajo trabajo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trabajo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCategoria = new SelectList(db.Categorias, "idCategoria", "categoria1", trabajo.idCategoria);
            ViewBag.idEstado = new SelectList(db.EstadoTrabajoes, "idEstado", "estadoTrabajo1", trabajo.idEstado);
            ViewBag.idUsuario = new SelectList(db.RegistroUsuarios, "idUsuario", "correo", trabajo.idUsuario);
            return View(trabajo);
        }

        // GET: Empresa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trabajo trabajo = db.Trabajoes.Find(id);
            if (trabajo == null)
            {
                return HttpNotFound();
            }
            return View(trabajo);
        }

        // POST: Empresa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trabajo trabajo = db.Trabajoes.Find(id);
            db.Trabajoes.Remove(trabajo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Views/Empresa/Create.cshtml
@model CapaEntidades.Trabajo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br />
<h2>Crear nuevo trabajo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Aqui podras crear trabajos nuevos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div id="global">
            <div class="form-group">
                @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idCategoria, "idCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idCategoria", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaInicial, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaInicial, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fechaInicial, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaAsignada, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaAsignada, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fechaAsignada, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idEstado, "idEstado", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idEstado", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idEstado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idUsuario, "idUsuario", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idUsuario", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idUsuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.costoTrabajo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.costoTrabajo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.costoTrabajo, "", new { @class = "text-danger" })
                </div>
            </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
   </div>
}

<h4>
    <a href='@Url.Action("Index", "Empresa")'>
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    </a>    Regresar
</h4>

WebApplication1/WebApplication1/Views/Empresa/Delete.cshtml
@model CapaEntidades.Trabajo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Trabajo</h2>

<h3>Estas seguro que desea eliminar?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaAsignada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaAsignada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.costoTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.costoTrabajo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.categoria1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.categoria1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoTrabajo.estadoTrabajo1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoTrabajo.estadoTrabajo1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistroUsuario.correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistroUsuario.correo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
        <h4>
            <a href='@Url.Action("Index", "Empresa")'>
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
            </a>    Regresar
        </h4>
    }
</div>

WebApplication1/WebApplication1/Views/Empresa/Details.cshtml
@model CapaEntidades.Trabajo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles de trabajo</h2>

<div>
    <h4>Aqui podras ver los detalles del trabajo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaAsignada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaAsignada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.costoTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.costoTrabajo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.categoria1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.categoria1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoTrabajo.estadoTrabajo1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoTrabajo.estadoTrabajo1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistroUsuario.correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistroUsuario.correo)
        </dd>

    </dl>
</div>

    <h4>
        @Html.ActionLink("Editar", "Edit", new { id = Model.idTrabajo })<br /><br />
        <a href='@Url.Action("Index", "Empresa")'>
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        </a>    Regresar
    </h4>
  

WebApplication1/WebApplication1/Views/Empresa/Edit.cshtml
@model CapaEntidades.Trabajo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br />

<h2>Actualizar datos de trabajo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idTrabajo)

<div id="global">      
         <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idCategoria, "idCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCategoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaInicial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaInicial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaAsignada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaAsignada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaAsignada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idEstado, "idEstado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idEstado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEstado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idUsuario, "idUsuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idUsuario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.costoTrabajo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.costoTrabajo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.costoTrabajo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</div>
}
<br />
<h4>
    <a href='@Url.Action("Index", "Empresa")'>
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    </a>    Regresar
</h4>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

WebApplication1/WebApplication1/Views/Empresa/Free.cshtml
@model IEnumerable<CapaEntidades.Trabajo>

@{
    ViewBag.Title = "Free";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Free</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaInicial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaAsignada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.costoTrabajo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.categoria1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoTrabajo.estadoTrabajo1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistroUsuario.correo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaInicial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaAsignada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaFinal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.costoTrabajo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria.categoria1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoTrabajo.estadoTrabajo1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistroUsuario.correo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.idTrabajo }) |
            @Html.ActionLink("Details", "Details", new { id=item.idTrabajo }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.idTrabajo })
        </td>
    </tr>
}

</table>

WebApplication1/WebApplication1/Views/Empresa/Index.cshtml
@model IEnumerable<CapaEntidades.Trabajo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<h2>Bienvenido @Session["nombreUsuario"] - Dashboard</h2>
<h4>Aqui podras ver todos aquellos trabajosreistrados </h4>

<button type="submit" class="Botones">@Html.ActionLink("Crear nuevo Trabajo", "Create")</button>
<br />
<br />
<div id="global">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaInicial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaAsignada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaFinal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.costoTrabajo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria.categoria1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstadoTrabajo.estadoTrabajo1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegistroUsuario.correo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaInicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaAsignada)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaFinal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.costoTrabajo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.categoria1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstadoTrabajo.estadoTrabajo1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegistroUsuario.correo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.idTrabajo }) |
                    @Html.ActionLink("Details", "Details", new { id=item.idTrabajo }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.idTrabajo })
                </td>
            </tr>
}

    </table>
</div>