WebApplication1/WebApplication1/Controllers/PRESENTACION/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaDatos;
using CapaEntidades;
using CapaNegocio;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {

        RepositorioRegistro _repoRegis = new RepositorioRegistro();
        //Proyecto_patronusWebEntities1
        //ProyectoPatronusWebEntities1 db = new ProyectoPatronusWebEntities1();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult dashboard()
        {
            return View();
        }

        /*EXTRAS*/
        public ActionResult conocenos()
        {
            return View();
        }

        public ActionResult contacto()
        {
            return View();
        }

        public ActionResult Servicios()
        {
            return View();
        }
    }
}

WebApplication1/WebApplication1/Controllers/PRESENTACION/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaDatos;
using CapaNegocio;
using CapaEntidades;

namespace WebApplication1.Controllers
{
    public class RegistroController : Controller
    {
        RepositorioRegistro _repo = new RepositorioRegistro();
        RepoF _repoF = new RepoF();
        //Proyecto_patronusWebEntities1
        ProyectoPatronusWebEntities db = new ProyectoPatronusWebEntities();
        // GET: Registro
        public ActionResult Registro()
        {
            //ViewBag.idTipoUsuario = new SelectList(db.TipoUsuarios, "idTipoUsuario", "TipoUsuario", 1);
            return View();
        }

        [HttpPost]
        public ActionResult Registro(RegistroUsuario user)
        {
            _repo.Crear(user);
            ModelState.Clear();
            ViewBag.Message = user.nombreUsuario + " registrado satisfactoriamente";
            //ViewBag.idTipoUsuario = new SelectList(db.TipoUsuarios, "idTipoUsuario", "TipoUsuario", user.idTipoUsuario);
            return View();
        }
    }
}

WebApplication1/WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="single">
    <div class="bg-empresarias-1 imagen-g texto-imagen">
        <p>¿Eres un profesionista y buscas trabajo?<br>- ¡Aquí encontrarás!</p>
        @*<div class="Botones">*@
            <button   class="Botones"> @Html.ActionLink("Registrarte", "Registro", "Registro")</button>
            
        @*</div>*@
        <p>¿Eres un empresario y necesitas quien te ayude con tu proyecto?<br>- ¡Llegaste al lugar indicado!</p>
    </div>
</div>

WebApplication1/WebApplication1/Views/Home/Servicios.cshtml
@{
    ViewBag.Title = "Servicios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br />
<h2>Servicios</h2>
<h4>Estamos en todos lados!<br /></h4>
<head>
    <title></title>
    <meta charset="utf-8" />
        @Scripts.Render("~/Scripts/jquery-1.10.2.js")


    <script>
     
            
        $(document).ready(function () {
            var ulEmployees = $('#ulEmployees');
                $.ajax({
                    type: 'GET',
                    url: "http://localhost:82/api/API",
                    dataType: 'json',
                    success: function (data) {
                        ulEmployees.empty();
                        $.each(data, function (index, val) {
                            var fullName = val.nombrePais;
                            ulEmployees.append( fullName + '<br />');
                        });
                    }
                });
          
        });
    </script>
</head>
<body>
    <table width="100%">
        <td width="50%">
            <img src="~/Content/Plantilla/img/mapa_mexico.png" width="500px"/>
        </td>
        <td width="50%">
            <ul id="ulEmployees" />
        </td>
    </table>
    <br /><br /><br /><br />
    <h4>Se parte del aquipo!! - @Html.ActionLink("Registrarte", "Registro", "Registro") <br /></h4>
</body>

WebApplication1/WebApplication1/Views/Home/conocenos.cshtml
@{
    ViewBag.Title = "conocenos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br />
<h2>Conocenos</h2>
<br /><br />
<table width="100%">
    <tr>
        <td width="50%">
            <p>Ernesto Jimenez - Programador</p>
            <img src="~/Content/Plantilla/img/netoman.jpg" width="200px" class="img-circle">
        </tdwidth="100%">
        <td width="50%">
            <p>Carmen Esqueda - Diseño</p>
            <img src="~/Content/Plantilla/img/carmen.jpg" width="200px" class="img-circle">
        </td>
    </tr>
    <tr></tr>
    <tr>
       <td width="25%">
           <h4>Mision</h4>
            <p>  Ayudar a las empresas con problemas usando como base la programación y así crear una aplicación la cual sea de ayuda.</p>
        </td>
        <td width="25%">
            <h4>Vision</h4>
            <p>Lograr que nuestro producto sea reconocido y se expanda a nivel internacional</p>
        </td>

     </tr>

</table>

WebApplication1/WebApplication1/Views/Home/contacto.cshtml
@{
    ViewBag.Title = "contacto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br />
<h2>Contacto</h2>
<br />

<table width="100%">
    <td width="50%">
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" class="form-control" placeholder="Nombre">
        </div>

        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" placeholder="Email">
        </div>

        <div class="form-group">
            <label>Asunto</label>
            <input type="text" class="form-control" placeholder="Asunto">
        </div>

        <div class="form-group">
            <label>Mensaje</label>
            <textarea class="form-control" rows="4">Mensaje</textarea>
        </div>

        <div class="form-group">
            <input class="btn btn-default" type="submit" value="Submit">
        </div>
    </td>
    <td width="50%">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6727.717221155542!2d-116.98710000000001!3d32.529923000000004!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x12c528793fc3f572!2sINSTITUTO+TECNOLOGICO+DE+TIJUANA!5e0!3m2!1ses!2smx!4v1481451712536" width="400" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
     </td>
</table>

WebApplication1/WebApplication1/Views/Home/dashboard.cshtml
@{
    ViewBag.Title = "dashboard";
}

<h2>dashboard</h2>
<div class="container">
    <table width="90%">
        <td width="30%">
            <button class="Botones"> @Html.ActionLink("Registrarte", "Registro", "Registro")</button><br />
            <button class="Botones"> @Html.ActionLink("Registrarte", "Registro", "Registro")</button><br />
        </td>
        <td width="60%">

        </td>
    </table>

</div