WebApplication1/WebApplication1/Controllers/USUARIO/FreelancerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CapaEntidades;

namespace WebApplication1.Controllers.USUARIO
{
    public class FreelancerController : Controller
    {
        private ProyectoPatronusWebEntities db = new ProyectoPatronusWebEntities();

        // GET: Freelancer
        public ActionResult Index()
        {
            var Trabajo = db.Trabajoes.Include(t => t.Categoria).Include(t => t.EstadoTrabajo).Include(t => t.RegistroUsuario).       // Sol mostrara los trabajos que tengan
                Where(a => a.idEstado == 1);                                                                                                                                            // un estado de no disponible (No asignado por empresa)
            return View(Trabajo.ToList());
        }

             // GET: Empresa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trabajo trabajo = db.Trabajoes.Find(id);
            if (trabajo == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCategoria = new SelectList(db.Categorias, "idCategoria", "categoria1", trabajo.idCategoria);
            ViewBag.idEstado = new SelectList(db.EstadoTrabajoes, "idEstado", "estadoTrabajo1", trabajo.idEstado);
            ViewBag.idUsuario = new SelectList(db.RegistroUsuarios, "idUsuario", "correo", trabajo.idUsuario);
            return View(trabajo);
        }

        // POST: Empresa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idTrabajo,titulo,descripcion,idCategoria,fechaInicial,fechaAsignada,fechaFinal,idEstado,idUsuario,costoTrabajo")] Trabajo trabajo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trabajo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCategoria = new SelectList(db.Categorias, "idCategoria", "categoria1", trabajo.idCategoria);
            ViewBag.idEstado = new SelectList(db.EstadoTrabajoes, "idEstado", "estadoTrabajo1", trabajo.idEstado);
            ViewBag.idUsuario = new SelectList(db.RegistroUsuarios, "idUsuario", "correo", trabajo.idUsuario);
            return View(trabajo);
        }







        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Views/Freelancer/Details - Copy.cshtml
@model CapaEntidades.Trabajo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div>
    <h4>Trabajo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaAsignada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaAsignada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.costoTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.costoTrabajo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.categoria1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.categoria1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoTrabajo.estadoTrabajo1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoTrabajo.estadoTrabajo1)

                <div class="form-group">
            @Html.LabelFor(model => model.idEstado, "idEstado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idEstado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEstado, "", new { @class = "text-danger" })
            </div>
        </div>


        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistroUsuario.correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistroUsuario.correo)

            <div class="form-group">
                @Html.LabelFor(model => model.idUsuario, "idUsuario", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idUsuario", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idUsuario, "", new { @class = "text-danger" })
                </div>
            </div>
        </dd>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idTrabajo }) |
    @Html.ActionLink("Back to List", "Index")
</p>
 }

WebApplication1/WebApplication1/Views/Freelancer/Edit.cshtml
@model CapaEntidades.Trabajo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Trabajo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <dl class="dl-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger", style = "display:none;" })
        @Html.HiddenFor(model => model.idTrabajo)


        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
            @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
            @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger", style = "display:none;" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger", style = "display:none;" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaInicial)
            @Html.EditorFor(model => model.fechaInicial, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
            @Html.ValidationMessageFor(model => model.fechaInicial, "", new { @class = "text-danger", style = "display:none;" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaAsignada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaAsignada)
            @Html.EditorFor(model => model.fechaAsignada, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
            @Html.ValidationMessageFor(model => model.fechaAsignada, "", new { @class = "text-danger", style = "display:none;" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaFinal)
            @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
            @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger", style = "display:none;" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.costoTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.costoTrabajo)
            @Html.EditorFor(model => model.costoTrabajo, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
            @Html.ValidationMessageFor(model => model.costoTrabajo, "", new { @class = "text-danger", style = "display:none;" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.categoria1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.categoria1)
            @Html.DropDownList("idCategoria", null, htmlAttributes: new { @class = "form-control", style = "display:none;" })
            @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger", style = "display:none;" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoTrabajo.estadoTrabajo1)
        </dt>

        <dd>

            @Html.DropDownList("idEstado", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idEstado, "", new { @class = "text-danger" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistroUsuario.correo)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.RegistroUsuario.correo)*@
            @Html.DropDownList("idUsuario", null, htmlAttributes: new { @class = "form-control"})
            @Html.ValidationMessageFor(model => model.idUsuario, "", new { @class = "text-danger" })
        </dd>









        @*<div class="form-group">
                @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.titulo, "", new {@class = "text-danger"  , style = "display:none;", style = "display:none;" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2", style = "display:none;" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new {@class = "text-danger"  , style = "display:none;"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idCategoria, "idCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idCategoria", null, htmlAttributes: new { @class = "form-control" , style = "display:none;"})
                    @Html.ValidationMessageFor(model => model.idCategoria, "", new {@class = "text-danger"  , style = "display:none;"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaInicial, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaInicial, new { htmlAttributes = new { @class = "form-control" , style = "display:none;"} })
                    @Html.ValidationMessageFor(model => model.fechaInicial, "", new {@class = "text-danger"  , style = "display:none;"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaAsignada, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaAsignada, new { htmlAttributes = new { @class = "form-control" , style = "display:none;"} })
                    @Html.ValidationMessageFor(model => model.fechaAsignada, "", new {@class = "text-danger"  , style = "display:none;"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control" , style = "display:none;"} })
                    @Html.ValidationMessageFor(model => model.fechaFinal, "", new {@class = "text-danger"  , style = "display:none;"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idEstado, "idEstado", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idEstado", null, htmlAttributes: new { @class = "form-control" , style = "display:none;"})
                    @Html.ValidationMessageFor(model => model.idEstado, "", new {@class = "text-danger"  , style = "display:none;"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idUsuario, "idUsuario", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idUsuario", null, htmlAttributes: new { @class = "form-control" , style = "display:none;"})
                    @Html.ValidationMessageFor(model => model.idUsuario, "", new {@class = "text-danger"  , style = "display:none;"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.costoTrabajo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.costoTrabajo, new { htmlAttributes = new { @class = "form-control" , style = "display:none;"} })
                    @Html.ValidationMessageFor(model => model.costoTrabajo, "", new {@class = "text-danger"  , style = "display:none;"})
                </div>
            </div>*@

    </dl>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">

            <input type="submit" value="Tomar trabajo!" class="btn btn-default" />
        </div>
    </div>
}
<h4>

    <a href='@Url.Action("Index", "Freelancer")'>
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    </a>     Regresar
</h4>

WebApplication1/WebApplication1/Views/Freelancer/Edit5.cshtml
@model IEnumerable<CapaEntidades.Trabajo>

@{
    ViewBag.Title = "Edit5";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit5</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaInicial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaAsignada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.costoTrabajo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.categoria1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoTrabajo.estadoTrabajo1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistroUsuario.correo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaInicial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaAsignada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaFinal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.costoTrabajo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria.categoria1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoTrabajo.estadoTrabajo1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistroUsuario.correo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.idTrabajo }) |
            @Html.ActionLink("Details", "Details", new { id=item.idTrabajo }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.idTrabajo })
        </td>
    </tr>
}

</table>

WebApplication1/WebApplication1/Views/Freelancer/Index.cshtml
@model IEnumerable<CapaEntidades.Trabajo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/Scripts/UpdateIdUsuario.js")
<br /><br />
<h2>Bienvenido @Session["nombreUsuario"] - Dashboard</h2>
<h4>Aqui podras ver todos los trabajos que estan disponibles para trabajar</h4>

<br />
<br />
<div id="global">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaInicial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaAsignada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaFinal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.costoTrabajo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria.categoria1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstadoTrabajo.estadoTrabajo1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegistroUsuario.correo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaInicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaAsignada)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaFinal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.costoTrabajo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.categoria1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstadoTrabajo.estadoTrabajo1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegistroUsuario.correo)
                </td>
                <td>
                    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js")
                    @Html.ActionLink("Details", "Edit", new { id=item.idTrabajo })

                </td>
            </tr>
}

    </table>
</div>